export const translations = {
  en: {
    nav: { dashboard: 'Dashboard', log: 'Log', analysis: 'Analysis', chat: 'Chat', profile: 'Profile', studio: 'Behavior studio', slogan: 'Track. Reflect. Adjust.', languageToggle:'KR/EN', logout:'Logout' },
    common: { loading: 'Loading Mindflow data...', refresh: 'Refresh', items: 'items', other: 'Other', daily:'Daily', weekly:'Weekly', today:'Today', yesterday:'Yesterday' },
    categories: { study:'Study', break:'Break', rest:'Rest', social_media:'Social Media', exercise:'Exercise', youtube:'YouTube', other:'Other' },
    mood: { happy:'Happy', neutral:'Neutral', stressed:'Stressed', focused:'Focused', motivated:'Motivated', anxious:'Anxious', sad:'Sad', distracted:'Distracted' },
    dashboard:{ heroDesc:'A calmer control room for your focus windows, distractions, and small daily wins.', routineFallback:'Your routines are becoming easier to read.', patternFallback:'Keep logging consistently and Mindflow will keep turning scattered moments into clear patterns.', protectFallback:'Your best hours are worth guarding from noise.', focus:'Focus', distraction:'Distraction', productive:'Productive', distracted:'Distracted', welcome:'Welcome back, {name}.', weekAtGlance:'Week at a glance', recentActivity:'Recent activity', latestNotes:'Latest notes', focusWindow:'Focus window', whatToProtect:'What to protect', riskZone:'Risk zone', momentum:'Momentum', dailyTimeline:'Daily Activity Timeline', focusVsDistraction:'Focus vs. distraction across the day', emotionTrends:'Emotion Trends', productiveEnergy:'Productive energy versus distracted energy', habitFrequency:'Habit Frequency', habitsThisWeek:'The behaviors showing up the most this week' },
    analysis:{ title:'AI Insights', description:'A pattern-focused view of where you drift, where you lock in, and what your next adjustment should be.', loading:'Loading AI insights...', loadError:'We couldn\'t load your AI insights.', empty:'No AI analysis available yet.', spotlight:'Pattern spotlight', spotlightFallback:'Your strongest signal is ready to act on.', spotlightDescFallback:'Mindflow compares recent behavior logs and surfaces the pattern most worth protecting or correcting next.', behaviorDistribution:'Behavior Distribution', behaviorDistributionDesc:'How your recent time splits across focus, neutral, and distracting behaviors', share:'Share', weeklyPattern:'Weekly Pattern', weeklyPatternDesc:'A time-of-day read on your productive rhythm', performance:'Performance', recommendedActions:'Recommended Actions' },
    profile:{ visualMomentum:'Visual Momentum', personalRhythm:'Personal Rhythm', profileSummary:'Profile summary', memberSince:'Member since {date}', totalBehaviors:'Total Behaviors', daysActive:'Days Active', currentStreak:'Current Streak', insightsGenerated:'Insights Generated' },
    command:{ hint:'Jump to...', log:'Log behavior', dashboard:'Go to dashboard', analysis:'Open analysis', profile:'Open profile', recent:'Recent' }
  },
  ko: {
    nav: { dashboard:'대시보드', log:'기록', analysis:'분석', chat:'채팅', profile:'프로필', studio:'행동 스튜디오', slogan:'기록하고, 돌아보고, 조정하세요.', languageToggle:'KR/EN', logout:'로그아웃' },
    common: { loading:'Mindflow 데이터를 불러오는 중...', refresh:'새로고침', items:'개', other:'기타', daily:'일별', weekly:'주별', today:'오늘', yesterday:'어제' },
    categories: { study:'공부', break:'휴식', rest:'휴식', social_media:'소셜 미디어', exercise:'운동', youtube:'유튜브', other:'기타' },
    mood: { happy:'행복', neutral:'보통', stressed:'스트레스', focused:'집중', motivated:'동기부여', anxious:'불안', sad:'슬픔', distracted:'산만' },
    dashboard:{ heroDesc:'집중 시간과 방해 요소, 작은 성장을 한눈에 보는 공간입니다.', routineFallback:'당신의 루틴이 점점 더 선명해지고 있어요.', patternFallback:'꾸준히 기록하면 흩어진 순간이 명확한 패턴으로 바뀝니다.', protectFallback:'가장 좋은 시간을 소음으로부터 지켜주세요.', focus:'집중', distraction:'방해', productive:'생산적', distracted:'산만', welcome:'다시 오신 것을 환영해요, {name}.', weekAtGlance:'한눈에 보는 이번 주', recentActivity:'최근 활동', latestNotes:'최신 기록', focusWindow:'집중 구간', whatToProtect:'지켜야 할 시간', riskZone:'위험 시간대', momentum:'추진력', dailyTimeline:'일일 활동 타임라인', focusVsDistraction:'하루 집중/방해 패턴', emotionTrends:'감정 추이', productiveEnergy:'생산 에너지 vs 산만 에너지', habitFrequency:'습관 빈도', habitsThisWeek:'이번 주 자주 나타난 행동' },
    analysis:{ title:'AI 인사이트', description:'흐트러지는 지점과 집중되는 지점을 보고 다음 조정을 제안합니다.', loading:'AI 인사이트를 불러오는 중...', loadError:'AI 인사이트를 불러오지 못했습니다.', empty:'아직 AI 분석이 없습니다.', spotlight:'패턴 스포트라이트', spotlightFallback:'지금 바로 실행할 수 있는 핵심 신호가 있어요.', spotlightDescFallback:'최근 기록을 비교해 지금 가장 보호/수정이 필요한 패턴을 보여줍니다.', behaviorDistribution:'행동 분포', behaviorDistributionDesc:'최근 시간이 집중/중립/방해 행동으로 어떻게 나뉘는지', share:'비율', weeklyPattern:'주간 패턴', weeklyPatternDesc:'시간대별 생산 리듬 보기', performance:'퍼포먼스', recommendedActions:'추천 액션' },
    profile:{ visualMomentum:'비주얼 모멘텀', personalRhythm:'개인 리듬', profileSummary:'프로필 요약', memberSince:'가입일 {date}', totalBehaviors:'총 행동 수', daysActive:'활동 일수', currentStreak:'현재 연속 기록', insightsGenerated:'생성된 인사이트' },
    command:{ hint:'이동할 메뉴를 선택하세요...', log:'기록하기', dashboard:'대시보드로 이동', analysis:'분석 열기', profile:'프로필 열기', recent:'최근 활동' }
  }
};
